### PR TITLE
progress bar, countdown, refactoring validation and bugfix

### PR DESCRIPTION
**Pull request by renan028**

### CODE REVIEW

**Comment by doudou** [comment]
Are you getting a review from @elael ?

**Comment by doudou** [comment]
@alcantara09 just noticed, wrong repository, need to re-create this PR to the thirteen fork

**Comment by elael** [comment]
That explains a lot, why it was so behind.

**Comment by renan028** [comment]
yes, Elael is reviewing.
I realized that when I did the pull request. But I made another pull request for the thirteen fork:
https://github.com/ThirteenLtda/planning-coating_trajectories/pull/4

**Comment by doudou** [comment]
OK, let's close this one then

**Pull request closed without merging**
